services:
  django:
    image: telasttechnologies/spm_django:main
    container_name: django-spm
    networks:
      - nginx_default
    depends_on:
      - postgres
    volumes:
     - spm_locale:/app/locale/
     - spm_media:/app/media/
     - spm_static:/app/static/
     - spm_staticfiles:/app/staticfiles/
    env_file:
      - ./docker/.envs/.qa/.django
      - ./docker/.envs/.qa/.postgres
    command: /start

  postgres:
    image: telasttechnologies/spm_postgres:main
    container_name: postgres-spm
    networks:
      - nginx_default
    ports:
      - "5441:5432"  # Host port:Container port
    volumes:
      - spm_postgres_data:/var/lib/postgresql/data
      - spm_postgres_data_backups:/backups
    env_file:
      - ./docker/.envs/.qa/.postgres

volumes:
  spm_postgres_data: {}
  spm_postgres_data_backups: {}
  spm_locale: {}
  spm_media: {}
  spm_static: {}
  spm_staticfiles: {}

networks:
  nginx_default:
    external: true
