# Generated by Django 5.0 on 2026-03-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('small_business', 'Small Business'), ('startup', 'Startup'), ('corporation', 'Corporation')], max_length=50),
        ),
    ]
